### ISSUE TITLE
Invalid 'tools': array too long. Expected an array with maximum length 128, but got an array with length 325 instead.

### ISSUE THREAD

**Issue by kevinLuan** [vishalmysore/Tools4AI#16]
dev.ai4j.openai4j.OpenAiHttpException: {
  "error": {
    "message": "Invalid 'tools': array too long. Expected an array with maximum length 128, but got an array with length 325 instead.",
    "type": "invalid_request_error",
    "param": "tools",
    "code": "array_above_max_length"
  }
}

How should this kind of problem be solved?

**Comment by vishalmysore** [comment]
Can you please send me the complete logs you can enable the debugging by using -Dtools4ai.log=debug

**Comment by kevinLuan** [comment]
> Can you please send me the complete logs you can enable the debugging by using -Dtools4ai.log=debug

17:00:08.015  WARN 60463 --- [nio-8080-exec-1] dev.langchain4j.internal.RetryUtils      : Exception was thrown on attempt 2 of 3

dev.ai4j.openai4j.OpenAiHttpException: {
  "error": {
    "message": "Invalid 'tools': array too long. Expected an array with maximum length 128, but got an array with length 309 instead.",
    "type": "invalid_request_error",
    "param": "tools",
    "code": "array_above_max_length"
  }
}
	at dev.ai4j.openai4j.Utils.toException(Utils.java:8)
	at dev.ai4j.openai4j.SyncRequestExecutor.execute(SyncRequestExecutor.java:28)
	at dev.ai4j.openai4j.RequestExecutor.execute(RequestExecutor.java:59)
	at dev.langchain4j.model.openai.OpenAiChatModel.lambda$generate$0(OpenAiChatModel.java:153)
	at dev.langchain4j.internal.RetryUtils$RetryPolicy.withRetry(RetryUtils.java:192)
	at dev.langchain4j.internal.RetryUtils.withRetry(RetryUtils.java:229)
	at dev.langchain4j.model.openai.OpenAiChatModel.generate(OpenAiChatModel.java:153)
	at dev.langchain4j.model.openai.OpenAiChatModel.generate(OpenAiChatModel.java:118)

**Comment by kevinLuan** [comment]
This limitation is caused by the maximum limit of OPEN AI on the number of tools to 128, in fact, I would like to ask, I define a lot of tool functions in the system, when the user talks with AI, AI understands all the functions defined by the system function, and AI determines the user's intention to trigger the call of the specified tool function
